### ISSUE TITLE
nr of satellites

### ISSUE THREAD

**Issue by WimSanders** [kristjanbjarni/opentx-widgets#5]
is it possible to show the number of satellites in the GPS widget?

**Comment by kristjanbjarni** [comment]
It's not really needed because you can just show telemetry value as a different value widget, it usually has the name "Sats". The design philosophy for these widgets was to display only one simple value and use instead the layout feature of the widget screen to combine information. I would recommend to use EdgeTX instead of OpenTX because it has a lot more layout and sizes to use if you are interested in better layout for telemetry screen.

**Comment by WimSanders** [comment]
I want to use your lua script as the basis for something I want to write myself. Lua is completely new to me and especially the interface with Open TX. I usually program in C++.
I'll stick with Open TX for a while because I'm starting to get a little familiar with it now
What I want to make is a screen in two parts.
On the left your customized Loop script containing the GPS of the aircraft and the GPS of my transmitter (as you may know my Horis X12S has a built-in GPS.)
In the right screen your home Lua, but then he must display the position of the aircraft from the home position (in case of a crash to find the aircraft again.

From the internal GPS I can already read the number of satellites and the GPS location. it would be nice if I could also read the number of satellites from the GPS in 
![screen-2023-02-23-125901](https://user-images.githubusercontent.com/24661114/220926120-b3d5bd54-eefa-4e02-8ad7-0c688776d36e.gif)
the plane.
In my telemerie screen I don't see any "sats" so I doubt if my Fr-Sky GPS is transmitting this data

**Comment by kristjanbjarni** [comment]
Yes it seems you don't have any Sats in your telemetry and that unfortunately means it can't be displayed. I think the FrSky protocol doesn't support sending Sats.

**Comment by kristjanbjarni** [comment]
>I've discovered a small bug in your lua script. The total number of km is not reported in km but in meters. division by 1000 still to be done: wgt.gpsTotalDistSTR = string.format("%.2f",(wgt.gpsTotalDist/1000))

I think you must be referencing some other project.

**Comment by WimSanders** [comment]
sorry different project.
