### ISSUE TITLE
A little Help

### ISSUE THREAD

**Issue by jan5650** [kristjanbjarni/opentx-widgets#6]
Hello!

I am working on a project for which I need the help of a competent person. From the widgets you have written I can see that you could definitely help me, because I need a very similar widget just slightly reworked.

Could we have a word about it?
I wrote to you on Facebook, maybe we can talk there?

**Comment by kristjanbjarni** [comment]
Maybe let's see I am pretty busy these days but drop me a line. I didn't however see any request on Facebook. If you want to use or modify some of the code for your own projects, absolutely feel free to do so, just a link or mention to the original project would be nice.
